<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TourSeeder extends Seeder
{
    public function run()
    {
        $tours = [
            [
                'name' => 'Pemandian Cibulan',
                'description' => 'Pemandian alami yang dihuni ikan dewa, dengan suasana sejuk dan air jernih.',
                'address' => 'Desa Manis Kidul, Kecamatan Jalaksana, Kabupaten Kuningan, Jawa Barat',
                'contact' => '',
                'opened' => '08:00:00',
                'closed' => '17:00:00',
                'image' => 'pemandian_cibulan.jpg',
                'longtitude' => 108.4950,
                'latitude' => '-6.9450',
                'price' => 15000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Telaga Biru Cicerem',
                'description' => 'Danau jernih berwarna biru dengan suasana alami, cocok untuk healing dan foto.',
                'address' => 'Desa Kaduela, Kecamatan Pasawahan, Kabupaten Kuningan, Jawa Barat',
                'contact' => '',
                'opened' => '08:00:00',
                'closed' => '17:00:00',
                'image' => 'telaga_biru.jpg',
                'longtitude' => 108.4820,
                'latitude' => '-6.9270',
                'price' => 10000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Curug Sidomba',
                'description' => 'Air terjun dengan nuansa asri, tersedia taman bermain dan tempat piknik keluarga.',
                'address' => 'Desa Peusing, Kecamatan Jalaksana, Kabupaten Kuningan',
                'contact' => '',
                'opened' => '08:00:00',
                'closed' => '17:00:00',
                'image' => 'curug_sidomba.jpg',
                'longtitude' => 108.5250,
                'latitude' => '-6.9550',
                'price' => 12000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Taman Nasional Gunung Ciremai',
                'description' => 'Area konservasi Gunung Ciremai dengan jalur pendakian populer dan pemandangan indah.',
                'address' => 'Kecamatan Cigugur & Jalaksana, Kabupaten Kuningan',
                'contact' => '',
                'opened' => '00:00:00',
                'closed' => '23:59:00',
                'image' => 'ciremai_national_park.jpg',
                'longtitude' => 108.4030,
                'latitude' => '-6.8920',
                'price' => 5000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Waduk Darma',
                'description' => 'Bendungan dengan panorama indah, cocok untuk piknik, naik perahu, dan wisata keluarga.',
                'address' => 'Desa Jagara, Kecamatan Darma, Kabupaten Kuningan',
                'contact' => '',
                'opened' => '08:00:00',
                'closed' => '17:00:00',
                'image' => 'waduk_darma.jpg',
                'longtitude' => 108.4760,
                'latitude' => '-7.0000',
                'price' => 10000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kebun Raya Kuningan',
                'description' => 'Taman konservasi flora tropis seluas 156 hektar untuk wisata dan edukasi.',
                'address' => 'Desa Padabeunghar, Kecamatan Pasawahan, Kabupaten Kuningan',
                'contact' => '',
                'opened' => '08:00:00',
                'closed' => '16:00:00',
                'image' => 'kebun_raya.jpg',
                'longtitude' => 108.4800,
                'latitude' => '-6.9200',
                'price' => 15000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sangkan Resort Aqua Park',
                'description' => 'Waterpark modern dengan berbagai wahana air untuk anak dan keluarga.',
                'address' => 'Jalan Raya Bandorasa, Kuningan',
                'contact' => '',
                'opened' => '09:00:00',
                'closed' => '17:00:00',
                'image' => 'sangkan_resort.jpg',
                'longtitude' => 108.4870,
                'latitude' => '-6.9220',
                'price' => 25000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Curug Putri Palutungan',
                'description' => 'Air terjun eksotis di tengah hutan pinus, cocok untuk tracking dan camping.',
                'address' => 'Desa Cisantana, Cigugur, Kuningan',
                'contact' => '',
                'opened' => '07:00:00',
                'closed' => '17:00:00',
                'image' => 'curug_putri.jpg',
                'longtitude' => 108.5000,
                'latitude' => '-6.9300',
                'price' => 10000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Situ Wulukut',
                'description' => 'Situ atau danau kecil dengan udara sejuk dan suasana hening cocok untuk healing.',
                'address' => 'Desa Kertayuga, Kecamatan Nusaherang, Kabupaten Kuningan',
                'contact' => '',
                'opened' => '07:00:00',
                'closed' => '18:00:00',
                'image' => 'situ_wulukut.jpg',
                'longtitude' => 108.4500,
                'latitude' => '-6.9600',
                'price' => 8000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gedung Perundingan Linggarjati',
                'description' => 'Situs sejarah perundingan Indonesia-Belanda tahun 1946, lengkap dengan museum.',
                'address' => 'Desa Linggarjati, Kecamatan Cilimus, Kabupaten Kuningan',
                'contact' => '',
                'opened' => '08:00:00',
                'closed' => '16:00:00',
                'image' => 'gedung_linggarjati.jpg',
                'longtitude' => 108.4890,
                'latitude' => '-6.9150',
                'price' => 5000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('tours')->insert($tours);
    }
}
